### ISSUE TITLE
Cassandra_cqlsh - acceptable commands for 'execute'

### ISSUE THREAD

**Issue by tlb1galaxy** [ansible-collections/community.cassandra#126]
##### SUMMARY

I didn't want to open a bug as this is more of usability issue than a function issue.  Apologies if this is the incorrect category.
Needed to clarify the scope of acceptable commands via 'execute' field.
I am basically trying to change the replication of keyspace 'system_auth'.  I found out after trying for some time the cassandra_keyspace does not support this (took some time to read the 1st line in docs).
So I would nromally do this via cqlsh command line.  Want to know if this is even supported via the module.
Command:
`ALTER KEYSPACE system_auth WITH REPLICATION= {'class':'NetworkTopologyStrategy','datacentre001':3};`

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

cassandra_keyspace
cassandra_cqlsh
##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/library/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

**Comment by rhysmeister** [comment]
Ideally the module will run anything.. I construct a shell command with clqsh. Do you have a specific example that works with cqlsh but not via the module? The single quotes probably need to be escaped but it might be easier to run the commands via the file parameter.

**Comment by tlb1galaxy** [comment]
I would normally run this via the cqlsh command to alter the replication.

`ALTER KEYSPACE system_auth WITH REPLICATION= {'class':'NetworkTopologyStrategy','datacenter001':3};`

I have been trying to get the syntax correct for the system not to parse partial line.
So far the following have not worked:
```
execute: >
              'ALTER KEYSPACE system_auth WITH REPLICATION= {'class':'NetworkTopologyStrategy','datacenter001':3}'

execute: >
             " 'ALTER KEYSPACE system_auth WITH REPLICATION= {'class':'NetworkTopologyStrategy','datacenter001':3}'"

execute:  'ALTER KEYSPACE system_auth WITH REPLICATION= {'class':'NetworkTopologyStrategy','datacenter001':3}'

execute: >
              'ALTER KEYSPACE system_auth WITH REPLICATION= {'class':'NetworkTopologyStrategy','datacenter001':3}'
```


I did just get this to work but the escaping is very ugly.  So I know it is not a limitation of the module but the Ansible parser.
`execute: "'ALTER KEYSPACE system_auth WITH REPLICATION= '{''''class'''':'''NetworkTopologyStrategy'''','''tlb1''':3}'"`

**Comment by tlb1galaxy** [comment]
I gave up on the 'execute' part.  No matter what I tried, it would not work.
I was able to successfully get the command to run via the file suggestion field.
Thanks

**Comment by rhysmeister** [comment]
I think the problem here is related to the fact you probably need to escape twice, once in yaml and the other for the shell. I would have expected the four quotes one to have works.... not sure why it didn't but that's ugly anyway. I've had a minor change in the code that seems to work. If the provided command contains single quotes I now quote the command the double quotes instead of single quotes... otherwise it behaves as before... https://github.com/ansible-collections/community.cassandra/pull/128

**Comment by rhysmeister** [comment]
You can pick up this change from https://github.com/ansible-collections/community.cassandra/releases/tag/latest

**Comment by tlb1galaxy** [comment]
Hello,
Thanks for the fix.  I will test this over the next few days.
