### ISSUE TITLE
GH pages disabled

### ISSUE THREAD

**Issue by allergencore** [ansible-collections/community.cassandra#200]
##### SUMMARY

Branch for GitHub pages exists, but they are disabled, only way to read docs is to checkout to that branch or to read the python sources.
Also, pls fix the link to docs on galaxy.ansible.com

##### ISSUE TYPE
- Documentation

##### COMPONENT NAME

\*
##### ANSIBLE VERSION

```paste below
2.9.25 / btw doesn't matter
```

**Comment by rhysmeister** [comment]
Hello,

GH-Pages were/are not disabled, available here https://ansible-collections.github.io/community.cassandra/

Link updated in galaxy.yml https://github.com/ansible-collections/community.cassandra/pull/201

Rhys
