### ISSUE TITLE
Got time out error from cassandra

### ISSUE THREAD

**Issue by sebinn09** [ansible-collections/community.cassandra#207]
---This is the error i got.because of not getting response from cassandra pod my application pod got restarted.I couldn't find any error logs from that application pod.

INFO  [SharedPool-Worker-137] 2022-01-31 20:18:30,020 Message.java:609 - Unexpected exception during request; channel = [id: 0x3a2a0bf5, L:/192.168.148.12:9042 ! R:/192.168.148.44:33936]

io.netty.channel.unix.Errors$NativeIoException: syscall:read(...)() failed: Connection reset by peer

    at io.netty.channel.unix.FileDescriptor.readAddress(...)(Unknown Source) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]

INFO  [SharedPool-Worker-34] 2022-01-31 20:18:30,020 Message.java:609 - Unexpected exception during request; channel = [id: 0x8d014349, L:/192.168.148.12:9042 ! R:/192.168.174.183:35744]

io.netty.channel.unix.Errors$NativeIoException: syscall:read(...)() failed: Connection reset by peer

    at io.netty.channel.unix.FileDescriptor.readAddress(...)(Unknown Source) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]

INFO  [Service Thread] 2022-01-31 20:18:32,465 GCInspector.java:284 - ParNew GC in 237ms.  CMS Old Gen: 1140193672 -> 1198931112; Par Eden Space: 167772160 -> 0;

**Comment by rhysmeister** [comment]
Hello @sebinn09,

This is the repository for the Cassandra Ansible Collection - https://galaxy.ansible.com/community/cassandra

For general Cassandra support you're probably best using one of the mailing list...

https://cassandra.apache.org/_/community.html#discussions

Cheers,

Rhys
