### ISSUE TITLE
Typo in argument name

### ISSUE THREAD

**Issue by pflorczyk** [ansible-collections/community.cassandra#273]
##### SUMMARY

There is small typo in argument name in 2 modules. data_centres should be renamed to data_centers.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cassandra_keyspace
cassandra_role

**Comment by rhysmeister** [comment]
Hi @pflorczyk,

There's no typo. The correct British Spelling is "centre". "Center" is an American English spelling. I'm from near London so old habits die hard!

https://www.grammarly.com/blog/center-centre/

You can add an alias if it bothers you.

Cheers,

Rhys

**Comment by pflorczyk** [comment]
I didn't know that. Thank you for explanation :)
It doesn't bother me but it's inconsistent with other modules (cassandra_role, cassandra_status)/code from this repo and cassandra itself.

**Comment by rhysmeister** [comment]
cassandra_role actually already has the alias but cassandra_keyspace did not. I've added this and made them a bit more consistent in https://github.com/ansible-collections/community.cassandra/pull/274

Cheers,

Rhys
